### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by johnathanmartin** [TrevorBagels/PulsepointScraperV2#1]
```
root@pulsepoint:~/PulsepointScraperV2# python3 -m dev
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/PulsepointScraperV2/dev/__main__.py", line 2, in <module>
    from .main import Main
  File "/root/PulsepointScraperV2/dev/main.py", line 1, in <module>
    from .core import scrape
  File "/root/PulsepointScraperV2/dev/core/scrape.py", line 10, in <module>
    from . import data as D
  File "/root/PulsepointScraperV2/dev/core/data.py", line 1, in <module>
    from ..prodict import Prodict
  File "/root/PulsepointScraperV2/dev/prodict/__init__.py", line 315, in <module>
    def dict_of_prodict_to_dict_of_dict(vv:dict[str, Prodict]) -> dict:
TypeError: 'type' object is not subscriptable
```

Config file:

```
{
    "api_key": "a",
    "pushover_token": "pushover application token",
    "pushover_user": "pushover user token",
    "scan_interval": "1m",
    "radius_default": "100m",
    "agencies": [
        "Los Angeles Fire Department (Valley Bureau)"
    ],
    "locations": [
        "Porter Ranch, CA 91326"
    ]
}
```

Fresh install, not sure where to look for the guidance of next steps.

**Comment by johnathanmartin** [comment]
Installed Python3.9, along with PIP 3.9 and modified config to look like:

```

{
    "api_key": "a",
    "pushover_token": "pushover application token",
    "pushover_user": "pushover user token",
    "scan_interval": "1m",
    "radius_default": "100m",
    "agencies": [
            {
                    "name": "Los Angeles Fire Department (Valley Bureau)"
            }
    ],
    "locations": [
            {       "name": "home",
                    "address": "Porter Ranch, CA 91326"}
    ]
}
```
