### ISSUE TITLE
Missing pymongo

### ISSUE THREAD

**Issue by Brinsby** [TrevorBagels/PulsepointScraperV2#5]
When I try to run the ppdb portion of the project I get an error 

` ~/Desktop/PulsepointScraperV2 (main)
$ python -m dev.ppdb
Traceback (most recent call last):
  File "C:\Users\O\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\O\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\O\Desktop\PulsepointScraperV2\dev\ppdb\__main__.py", line 1, in <module>
    from . import ppdb
  File "C:\Users\O\Desktop\PulsepointScraperV2\dev\ppdb\ppdb.py", line 2, in <module>
    from ..prodict import Prodict
  File "C:\Users\O\Desktop\PulsepointScraperV2\dev\prodict\__init__.py", line 315, in <module>
    def dict_of_prodict_to_dict_of_dict(vv:dict[str, Prodict]) -> dict:
TypeError: 'type' object is not subscriptable`

When I look at the offending line
  `def dict_of_prodict_to_dict_of_dict(vv:dict[str, Prodict]) -> dict:`
  It looks like it is saying you cannot subscript the param because its an object but this looks like you naming a function param vv as a dict type which you should be able to do to my knowledge so I am not really sure why this is happening

**Comment by TrevorBagels** [comment]
I think that's an issue caused by an older version of python. Python 3.9 should work with this line, I'll test it when I get home.
